keep_columns:
    - lat
    - lon
    - l1
    - l2
    - l3           
    - surface_total
    - property_type       
    - operation_type
    - price
    - currency
drop_rows:
  countries: 
    - Brasil
    - Estados Unidos
    - Estados Unidos de América
  nan:
    - price
    - currency
    - lat
    - lon
  duplicates:
    - lat 
    - lon
    - surface_total
    - property_type
    - price
outliers_percentile:
  price:
    lower: 5
    upper: 95